# Site settings

# REQUIRED CHANGES
# Edit next line, providing your own name.
title: Hayden Tsui  | Professional Portfolio
# Edit next line, replacing 'techfolios' with your github username
url: "https://haydentsui.github.io"
# Edit next line so that baseurl is "" if your repo is <username>.github.io
baseurl: ""

# OPTIONAL CHANGES
# You might want to change the bio page label to something else, such as CV
bio-page-label: Resume
# You might want to change the theme associated with one or more sections of the site.
# Defining your own custom theme variations is easy. See the documentation.
theme-home: theme-home-builtin-1.html
theme-projects: theme-projects-builtin-1.html
theme-essays: theme-essays-builtin-1.html
theme-bio: theme-bio-builtin-1.html

# Specify the rouge syntax highlighter theme. Pick one from css/rouge.
rouge-theme: igorpro

# YOU NORMALLY NEVER CHANGE THE FOLLOWING
markdown: kramdown
include: [_data]

#############################
#        TO FILL            #
#############################

# The title that appears on the tab
#title: Hayden Tsui's Gallery

# The title on the web page
full_name: Hayden Tsui

# The type of layout
# Options: ROWS, SQUARES, COLUMNS
layout_style: ROWS

# Variables below are default. Feel free to customize the values below, but do
# not remove the property.

# Integer: Spacing between each photo
spacing: 10

# Boolean(true|false): Shuffle the photos in the album
shuffle: false

# Integer: Number of columns for square or columns
columns: 4

# Integer: Max height for rows
max_height: 400

# Handle
instagram: haydentsui

######################
# END OF CONFIG CODE #
#  Ignore below :)   #
######################
#
# Name of your gallery (this will show up at the top of your page and in the RSS feed)
name: Gallery

# Short description (goes below the title; it will also be used in the RSS feed)
description: Photography Portfolio

# Your name, as you want it to appear underneath each post and in the footer
author: Andy Zhang

# Your email if you want it to be linked on the contact page
author_email: andzhng@gmail.com

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog
baseurl: /path

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
# url: http://andyzhang.net/gallery